AntiIllegal:
  MaxItemNameLength: 51
  IllegalItems:
    - 'BEDROCK'
    - 'BARRIER'
    - 'END_PORTAL_FRAME'
    - 'SPAWNER'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - '*SPAWN_EGG*'
    - '*COMMAND_BLOCK*'
    - 'KNOWLEDGE_BOOK'
    - 'DIRT_PATH'
    - 'FARMLAND'
    - 'REINFORCED_DEEPSLATE'
ChatControl:
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 3
  #Blocked words
  Blocked: []
  CommandWhitelist:
    - "/ignore"
    - "/unignore"
    - "/togglechat"
    - "/toggledeathmsg"
    - "/msg"
    - "/message"
    - "/whisper"
    - "/tell"
    - "/w"
    - "/reply"
    - "/r"
    - "/home"
    - "/sethome"
    - "/delhome"
    - "/help"
    - "/plugins"
    - "/pl"
    - "/kill"
    - "/stats"
    - "/discord"