AntiIllegal:
  MaxItemNameLength: 51
  IllegalItems:
    - 'BEDROCK'
    - 'BARRIER'
    - 'END_PORTAL_FRAME'
    - 'SPAWNER'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - '*SPAWN_EGG*'
    - '*COMMAND_BLOCK*'
    - 'KNOWLEDGE_BOOK'
    - 'DIRT_PATH'
    - 'FARMLAND'
    - 'REINFORCED_DEEPSLATE'
AnnouncementInterval: 90 # In seconds
ChatControl:
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 5
  #Blocked words
  Blocked:
    - 'Anar Anarchy'
    - '5b5t'
    - 'Deja de buscar un servidor y gastar dinero comprando kits y mejor unete al mejor servidor con Kits y Sorteos 100% Grati'
    - 'snowanarchy'
    - 'demonmc'
    - 'snowan'
    - 'Anar'
    - 'AnarAnarchy'
    - '.org'
    - 'EndPortal'
    - 'endportal'
    - 'NetherPortal'
    - 'netherportal'
    - '89.35.49.34:19175'
    - 'SurvivalCraft'
    - 'Joooin'
    - '.at'
    - 'Join 89,35,49,34:19175 Semi-Anarchy Bedrock'
    - 'Semi-Anarchy'
    - 'Join'
    - 'Entra'
    - '89,35'
    - 'JOIN'
    - 'fuck 8b8t'
    - 'mc.latinomc.tk'
    - 'AnarchyLatam.ploudos.me'
    - 'anarchyvn.net'
    - '9aJSETCQTr'
    - 'Nar6nCnS8T'
    - 'gg/9aJSETCQTr'
    - 'gg/Nar6nCnS8T'
    - 'lunecraft'
    - '3b3t.shock.gg'
    - 'snowаnarchy,оrg'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒｇ ｈａ ａｂｉｅｒｔｏ ｓｕｓ ｐｕｅｒｔａｓ ａ ｊｕｇａｄｏｒｅｓ ｅｓｐａñｏｌｅｓ ｙ ｉｎｇｌｅｓｅｓ， ｅｎｔｒａ ｙ ｄｉｓｆｒｕｔａ'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒg'
    - 'chad-sigma-topg'
    - '3b3t,shock,gg'
    - '3b3t'
    - '3B3T'
    - 'DeathAnarchy.nether-zone.com'
    - '9b9t'
    - 'discord'
  CommandWhitelist:
    - "/ignore"
    - "/unignore"
    - "/togglechat"
    - "/toggledeathmsg"
    - "/msg"
    - "/message"
    - "/whisper"
    - "/tell"
    - "/w"
    - "/reply"
    - "/r"
    - "/home"
    - "/sethome"
    - "/delhome"
    - "/help"
    - "/plugins"
    - "/pl"
    - "/kill"
    - "/stats"
    - "/discord"
    - "/tpa"
    - "/tpayes"
    - "/tpano"
TPA:
  RequestTimeout: 3 # In minutes
TPS:
  Permissions:
    - 'leee.tps'
Home:
  #The closest the player can be to 0,0
  Radius: 500
  #Max homes a player can have
  MaxHomes: 3
Vote:
  MaxHomesByVoting: 10
  AddHomePermission: '8b8tcore.home.max.%d'
  Permissions: #List of permissions to give the player
    - 'leee.nc'
Patch:
  ElytraMaxSpeed: 56.9 #Max speed in blocks/second. Default value is the max speed reachable with firework rockets
  EntityPerChunk:
    CheckInterval: 1 #For normal entities (in minutes) (entity::min::max)
    TotalEntitiesPerChunk: 100
    TotalTileEntitiesPerChunk: 100
    DefaultEntitiesPerChunk: 50
    EntitiesPerChunk:
      - 'wither::20::30'
      - 'armor_stand::15::25'
      - 'boat::10::20'
      - 'minecart::10::20'
      - 'bat::10::20'
      - 'bee::10::20'
      - 'blaze::10::20'
      - 'cat::10::20'
      - 'cave_spider::10::20'
      - 'chicken::10::20'
      - 'cod::10::20'
      - 'cow::10::20'
      - 'creeper::10::20'
      - 'dolphin::10::20'
      - 'donkey::10::20'
      - 'drowned::10::20'
      - 'elder_guardian::10::20'
      - 'ender_dragon::10::20'
      - 'enderman::10::20'
      - 'endermite::10::20'
      - 'evoker::10::20'
      - 'fox::10::20'
      - 'ghast::10::20'
      - 'giant::10::20'
      - 'guardian::10::20'
      - 'hoglin::10::20'
      - 'horse::10::20'
      - 'husk::10::20'
      - 'illusioner::10::20'
      - 'iron_golem::10::20'
      - 'llama::10::20'
      - 'magma_cube::10::20'
      - 'mooshroom::10::20'
      - 'mule::10::20'
      - 'ocelot::10::20'
      - 'panda::10::20'
      - 'parrot::10::20'
      - 'phantom::10::20'
      - 'pig::10::20'
      - 'piglin::10::20'
      - 'piglin_brute::10::20'
      - 'pillager::10::20'
      - 'polar_bear::10::20'
      - 'pufferfish::10::20'
      - 'rabbit::10::20'
      - 'ravager::10::20'
      - 'salmon::10::20'
      - 'sheep::10::20'
      - 'shulker::10::20'
      - 'silverfish::10::20'
      - 'skeleton::10::20'
      - 'skeleton_horse::10::20'
      - 'slime::10::20'
      - 'snow_golem::10::20'
      - 'spider::10::20'
      - 'squid::10::20'
      - 'stray::10::20'
      - 'strider::10::20'
      - 'trader_llama::10::20'
      - 'tropical_fish::10::20'
      - 'turtle::10::20'
      - 'vex::10::20'
      - 'villager::10::20'
      - 'vindicator::10::20'
      - 'wandering_trader::10::20'
      - 'witch::10::20'
      - 'wither_skeleton::10::20'
      - 'wolf::10::20'
      - 'zoglin::10::20'
      - 'zombie::10::20'
      - 'zombie_horse::10::20'
      - 'zombie_villager::10::20'
      - 'zombified_piglin::10::20'
    DefaultTileEntitiesPerChunk: 50
    TileEntitiesPerChunk:
      - 'hopper::10::20'
      - 'dispenser::10::20'
      - 'dropper::10::20'
      - 'furnace::10::20'
      - 'brewing_stand::10::20'
      - 'beacon::10::20'
      - 'enchanting_table::10::20'
      - 'anvil::10::20'
      - 'ender_chest::10::20'
      - 'chest::10::20'
      - 'shulker_box::10::20'
      - 'barrel::10::20'
      - 'lectern::10::20'
      - 'loom::10::20'
      - 'cartography_table::10::20'
      - 'grindstone::10::20'
      - 'stonecutter::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
MaxRedstoneUpdatesPerTick: 100 #-1 to disable
Commands:
  # to send to the player for /discord
  Discord: '&3Join us on discord at&r&a https://discord.8b8t.me'
