AntiIllegal:
  MaxItemNameLength: 51
  IllegalItems:
    - 'BEDROCK'
    - 'BARRIER'
    - 'END_PORTAL_FRAME'
    - 'SPAWNER'
    - 'STRUCTURE_BLOCK'
    - 'STRUCTURE_VOID'
    - '*SPAWN_EGG*'
    - '*COMMAND_BLOCK*'
    - 'KNOWLEDGE_BOOK'
    - 'DIRT_PATH'
    - 'FARMLAND'
    - 'REINFORCED_DEEPSLATE'
AnnouncementInterval: 90 # In seconds
ChatControl:
  PreventLinks: true #Uses a list of all TLDs
  #How long before a player can chat again (In seconds)
  Cooldown: 5
  #Blocked words
  Blocked:
    - 'Anar Anarchy'
    - '5b5t'
    - 'Deja de buscar un servidor y gastar dinero comprando kits y mejor unete al mejor servidor con Kits y Sorteos 100% Grati'
    - 'snowanarchy'
    - 'demonmc'
    - 'snowan'
    - 'Anar'
    - 'AnarAnarchy'
    - '.org'
    - 'EndPortal'
    - 'endportal'
    - 'NetherPortal'
    - 'netherportal'
    - '89.35.49.34:19175'
    - 'SurvivalCraft'
    - 'Joooin'
    - '.at'
    - 'Join 89,35,49,34:19175 Semi-Anarchy Bedrock'
    - 'Semi-Anarchy'
    - 'Join'
    - 'Entra'
    - '89,35'
    - 'JOIN'
    - 'fuck 8b8t'
    - 'mc.latinomc.tk'
    - 'AnarchyLatam.ploudos.me'
    - 'anarchyvn.net'
    - '9aJSETCQTr'
    - 'Nar6nCnS8T'
    - 'gg/9aJSETCQTr'
    - 'gg/Nar6nCnS8T'
    - 'lunecraft'
    - '3b3t.shock.gg'
    - 'snowаnarchy,оrg'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒｇ ｈａ ａｂｉｅｒｔｏ ｓｕｓ ｐｕｅｒｔａｓ ａ ｊｕｇａｄｏｒｅｓ ｅｓｐａñｏｌｅｓ ｙ ｉｎｇｌｅｓｅｓ， ｅｎｔｒａ ｙ ｄｉｓｆｒｕｔａ'
    - 'ＳｎｏｗＡｎａｒｃｈｙ,ｏｒg'
    - 'chad-sigma-topg'
    - '3b3t,shock,gg'
    - '3b3t'
    - '3B3T'
    - 'DeathAnarchy.nether-zone.com'
    - '9b9t'
    - 'discord'
  CommandWhitelist:
    - '/ic'
    - '/nc'
    - '/ignore'
    - '/unignore'
    - '/togglechat'
    - '/toggledeathmsg'
    - '/msg'
    - '/message'
    - '/whisper'
    - '/tell'
    - '/w'
    - '/reply'
    - '/r'
    - '/home'
    - '/sethome'
    - '/delhome'
    - '/help'
    - '/nick'
    - '/plugins'
    - '/pl'
    - '/kill'
    - '/stats'
    - '/discord'
    - '/tpa'
    - '/tpayes'
    - '/tpano'
    - '/help'
    - '/worldstats'
    - '/stats'
    - '/discord'
    - '/joindate'
    - '/jd'
    - '/seen'
    - '/echest'
    - '/voicechat'
    - '/vote'
    - '/dupe'
TPA:
  RequestTimeout: 3 # In minutes
TPS:
  Permissions:
    - 'leee.tps'
Home:
  #The closest the player can be to 0,0
  Radius: 500
  #Max homes a player can have
  MaxHomes: 3
Vote:
  MaxHomesByVoting: 10
  AddHomePermission: '8b8tcore.home.max.%d'
  Permissions: #List of permissions to give the player
    - 'Leee.nc'
Patch:
  ElytraMaxSpeed: 56.9 #Max speed in blocks/second. Default value is the max speed reachable with firework rockets
  EntityPerChunk:
    CheckInterval: 1 #For normal entities (in minutes) (entity::min::max)
    TotalEntitiesPerChunk: 100
    TotalTileEntitiesPerChunk: 100
    DefaultEntitiesPerChunk: 50
    EntitiesPerChunk:
      - 'wither::20::30'
      - 'armor_stand::15::25'
      - 'boat::10::20'
    DefaultTileEntitiesPerChunk: 50
    TileEntitiesPerChunk:
      - 'hopper::10::20'
      - 'dispenser::10::20'
      - 'dropper::10::20'
      - 'furnace::10::20'
      - 'brewing_stand::10::20'
      - 'beacon::10::20'
      - 'enchanting_table::10::20'
      - 'anvil::10::20'
      - 'ender_chest::10::20'
      - 'chest::10::20'
      - 'shulker_box::10::20'
      - 'barrel::10::20'
      - 'lectern::10::20'
      - 'loom::10::20'
      - 'cartography_table::10::20'
      - 'grindstone::10::20'
      - 'stonecutter::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
      - 'smithing_table::10::20'
      - 'loom::10::20'
      - 'lectern::10::20'
      - 'grindstone::10::20'
      - 'smoker::10::20'
      - 'blast_furnace::10::20'
      - 'campfire::10::20'
      - 'composter::10::20'
      - 'bell::10::20'
      - 'jigsaw::10::20'
      - 'lantern::10::20'
      - 'scaffolding::10::20'
      - 'stonecutter::10::20'
      - 'cartography_table::10::20'
      - 'fletching_table::10::20'
MaxRedstoneUpdatesPerTick: 100 #-1 to disable
Commands:
  # to send to the player for /discord
  Discord: '&3Join us on discord at&r&a https://discord.8b8t.me'
