name: 8b8tCore
main: me.txmc.core.Main
version: 1.0.6
author: 254n_m
description: All the bullshit for 8b8t
api-version: 1.20
folia-supported: true
softdepend:
  - NuVotifier
commands:
  msg:
    aliases: [message, whisper, tell, w, t]
  reply:
    aliases: [r]
  ignore:
  togglechat:
  unignore:
  tpa:
  tpayes:
    aliases: [tpaaccept]
  tpano:
    aliases: [tpadeny]
  home:
  sethome:
  delhome:
  lef:
  discord:
  help:
  open:
  say:
  spawn:
  speed:
  uptime:
  world:
  vote: