name: 8b8tCore
main: me.txmc.core.Main
version: 1.0-SNAPSHIT
author: 254n_m
description: All the bullshit for 8b8t
api-version: 1.20
folia-supported: true
commands:
  msg:
    aliases: [message, whisper, tell, w, t]
  reply:
    aliases: [r]
  ignore:
  togglechat:
  unignore:
  tpa:
  tpayes:
    aliases: [tpaaccept]
  tpano:
    aliases: [tpadeny]
